name: Build

on:
  push:
    branches:
      - main

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: preview
  # build_ios:
  #   name: Build iOS App
  #   type: build
  #   params:
  #     platform: ios
  #     profile: preview
